name: Mutation Testing

# Mutation tests take a very long time to complete, as all unit tests are run with every mutation.
# As such, we only run them on the master branch, and only when a push is made to that branch.

on:
  push:
    branches:
      - master

jobs:
  mutation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages
          key: ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache mutmut results
        uses: actions/cache@v3
        id: mutmut-cache
        with:
          path: .mutmut-cache
          key: ${{ runner.os }}-mutmut-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-mutmut-

      - name: Run mutation tests
        continue-on-error: true
        run: mutmut run --paths-to-mutate "src/" --tests-dir "test/" --disable-mutation-types=string,decorator || true

      - name: Create mutation test report
        run: mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutmut-test.xml

      - name: Upload test case results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          comment_title: Mutation Testing
          fail_on: "errors"
          files: |
            mutmut-test.xml
