name: Run Systems Tests

# Reason: System tests take a _long_ time to run, since it has to
# build the Docker image. We're using the systems test as a smoke
# detector, so it doesn't have to run on every commit to a PR when
# it's open; CI should fail fast!

# It also doesn't make sense to publish the image to GitHub's package
# repository, since we're not releasing the Docker image; we're
# releasing the shell. So, it still make sense to build a fresh Docker
# image on every push.

# So, we only run this expensive test when a PR has been merged. If
# issues crop up then, a new PR should be opened to address those
# issues.

on:
  push:
    branches:
      - master

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  system-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages
          key: ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run systems test
        continue-on-error: true
        run: |
          docker build . -t comp0010-system-test
          python -m nose2 --plugin nose2.plugins.junitxml --junit-xml-path system-test.xml system_test

      - name: Upload test case results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Systems Tests
          files: |
            system-test.xml
