name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages
          key: ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        continue-on-error: true
        run: |
          export PYTHONPATH="$PWD/:$PWD/src"
          cd test/
          python -m coverage run --branch -m nose2 --plugin nose2.plugins.junitxml --junit-xml-path unit-test.xml
          cp unit-test.xml ../

      - name: Upload test case results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Unit Tests
          files: |
            unit-test.xml

      - name: Generate coverage report
        run: |
          cd test/
          python -m coverage xml

      - name: Upload coverage report
        uses: orgoro/coverage@v3.1
        if: github.event_name == 'pull_request'
        with:
          coverageFile: test/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0
          thresholdNew: 0.9
          thresholdModified: 0.9
